[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "latex_gen_assignment"
version = "1.1"
description = "A python homework"
readme = "README.md"
requires-python = ">=3.7"